name: kazlauskas.dev deployment
on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  web-deploy:
    name: 🚀 Deploy to kazlauskas.dev
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: 📦 Setup Node.js v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: 🔨 Build website
        run: |
          npm ci
          npm run build

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          local-dir: ./build/
          server-dir: public_html/
